module systems.glam.sdk {
  exports systems.glam.sdk.idl.programs.glam.config.gen.types;
  exports systems.glam.sdk.idl.programs.glam.config.gen;
  exports systems.glam.sdk.idl.programs.glam.drift.gen.types;
  exports systems.glam.sdk.idl.programs.glam.drift.gen;
  exports systems.glam.sdk.idl.programs.glam.jupiter;
  exports systems.glam.sdk.idl.programs.glam.kamino.gen.types;
  exports systems.glam.sdk.idl.programs.glam.kamino.gen;
  exports systems.glam.sdk.idl.programs.glam.mint.gen.types;
  exports systems.glam.sdk.idl.programs.glam.mint.gen;
  exports systems.glam.sdk.idl.programs.glam.policy.gen.types;
  exports systems.glam.sdk.idl.programs.glam.policy.gen;
  exports systems.glam.sdk.idl.programs.glam.protocol.gen.types;
  exports systems.glam.sdk.idl.programs.glam.protocol.gen;
  exports systems.glam.sdk.idl.programs.glam.spl.gen;
  exports systems.glam.sdk.lut;
  exports systems.glam.sdk.proxy;
  exports systems.glam.sdk;
  requires java.base;
  requires java.net.http;
  requires software.sava.solana_programs;
  requires transitive software.sava.core;
  requires transitive software.sava.idl.clients.core;
  requires transitive software.sava.idl.clients.drift;
  requires transitive software.sava.idl.clients.jupiter;
  requires transitive software.sava.idl.clients.kamino;
  requires transitive software.sava.idl.clients.marinade;
  requires transitive software.sava.idl.clients.meteora;
  requires transitive software.sava.idl.clients.spl;
  requires transitive software.sava.rpc;
  requires systems.comodal.json_iterator;
  requires transitive systems.glam.ix_proxy;
}
