systems.comodal.json_iterator=software.sava:json-iterator
software.sava.core=software.sava:sava-core
software.sava.rpc=software.sava:sava-rpc
software.sava.idl.clients.bundle=software.sava:idl-clients-bundle
software.sava.idl.clients.spl=software.sava:idl-clients-spl
software.sava.kms_core=software.sava:ravina-kms-core
software.sava.ravina_core=software.sava:ravina-core
software.sava.ravina_solana=software.sava:ravina-solana
systems.glam.ix_proxy=systems.glam:ix-proxy
