package systems.glam.services.db.sql;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.concurrent.TimeUnit;

final class ComposedPreparedStmtExecutor<R> extends RootStmtExecutor<R> {

  private final String statement;
  private final PreparedStmtExecutor<R> stmtExecutor;
  private final int autoGeneratedKeys;

  public ComposedPreparedStmtExecutor(final SqlDataSource datasource,
                                      final int maxRetrySleep, final TimeUnit timeUnit,
                                      final String statement,
                                      final int autoGeneratedKeys,
                                      final PreparedStmtExecutor<R> stmtExecutor) {
    super(datasource, maxRetrySleep, timeUnit);
    this.statement = statement;
    this.stmtExecutor = stmtExecutor;
    this.autoGeneratedKeys = autoGeneratedKeys;
  }

  @Override
  protected R execute(final Connection connection) throws SQLException {
    connection.setAutoCommit(true);
    try (final var preparedStatement = connection.prepareStatement(statement, autoGeneratedKeys)) {
      return stmtExecutor.execute(preparedStatement);
    }
  }
}
